package UI;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import User.UserController;

/**
 *
 * @author saisuryavarshith
 */
public class SignupForm extends javax.swing.JFrame {

    /**
     * Creates new form signUpForm
     */
    public SignupForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signUpF = new javax.swing.JPanel();
        leftLabel2 = new javax.swing.JPanel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        lname = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        ldob = new javax.swing.JLabel();
        laddress = new javax.swing.JLabel();
        taddress = new javax.swing.JTextField();
        tidnum = new javax.swing.JTextField();
        lidnum = new javax.swing.JLabel();
        tuname = new javax.swing.JTextField();
        luname = new javax.swing.JLabel();
        lpass = new javax.swing.JLabel();
        tpass = new javax.swing.JPasswordField();
        bsup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        signUpF.setPreferredSize(new java.awt.Dimension(1000, 600));

        leftLabel2.setBackground(new java.awt.Color(192, 39, 39));
        leftLabel2.setForeground(new java.awt.Color(242, 242, 242));
        leftLabel2.setPreferredSize(new java.awt.Dimension(755, 0));

        javax.swing.GroupLayout leftLabel2Layout = new javax.swing.GroupLayout(leftLabel2);
        leftLabel2.setLayout(leftLabel2Layout);
        leftLabel2Layout.setHorizontalGroup(
            leftLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        leftLabel2Layout.setVerticalGroup(
            leftLabel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        lname.setText("FULL NAME");

        ldob.setText("DOB");

        laddress.setText("ADDRESS");

        taddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taddressActionPerformed(evt);
            }
        });

        tidnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidnumActionPerformed(evt);
            }
        });

        lidnum.setText("ID NUMBER");

        tuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tunameActionPerformed(evt);
            }
        });

        luname.setText("USER NAME");

        lpass.setText("PASSWORD");

        bsup.setText("SIGN UP");
        bsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpFLayout = new javax.swing.GroupLayout(signUpF);
        signUpF.setLayout(signUpFLayout);
        signUpFLayout.setHorizontalGroup(
            signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpFLayout.createSequentialGroup()
                .addComponent(leftLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpFLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ldob, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signUpFLayout.createSequentialGroup()
                                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(signUpFLayout.createSequentialGroup()
                                        .addComponent(laddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(80, 80, 80))
                                    .addGroup(signUpFLayout.createSequentialGroup()
                                        .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lpass)
                                            .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lname)
                                                .addComponent(lidnum)
                                                .addComponent(luname)))
                                        .addGap(79, 79, 79)))
                                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tuname)
                                    .addComponent(taddress)
                                    .addComponent(tname)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                    .addComponent(tidnum)
                                    .addComponent(tpass))))
                        .addContainerGap(272, Short.MAX_VALUE))
                    .addGroup(signUpFLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bsup)
                        .addGap(53, 53, 53))))
        );
        signUpFLayout.setVerticalGroup(
            signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpFLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lname)
                    .addComponent(tname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ldob))
                .addGap(18, 18, 18)
                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laddress)
                    .addComponent(taddress, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lidnum))
                .addGap(18, 18, 18)
                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luname))
                .addGap(18, 18, 18)
                .addGroup(signUpFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpass)
                    .addComponent(tpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(169, 169, 169)
                .addComponent(bsup)
                .addGap(154, 154, 154))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpFLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(leftLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signUpF, javax.swing.GroupLayout.PREFERRED_SIZE, 1510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signUpF, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void taddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taddressActionPerformed

    private void tidnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidnumActionPerformed

    private void tunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tunameActionPerformed

    private void bsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsupActionPerformed
        // TODO add your handling code here:
        UserController.getInstance().addUser(tname.getText(), jDateChooser2.getDate(), taddress.getText(), tidnum.getText(), tuname.getText(), String.valueOf(tpass.getPassword()));
        dispose();
        LoginPage loginpage= new LoginPage();
        loginpage.setVisible(true); 
    }//GEN-LAST:event_bsupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsup;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel laddress;
    private javax.swing.JLabel ldob;
    private javax.swing.JPanel leftLabel2;
    private javax.swing.JLabel lidnum;
    private javax.swing.JLabel lname;
    private javax.swing.JLabel lpass;
    private javax.swing.JLabel luname;
    private javax.swing.JPanel signUpF;
    private javax.swing.JTextField taddress;
    private javax.swing.JTextField tidnum;
    private javax.swing.JTextField tname;
    private javax.swing.JPasswordField tpass;
    private javax.swing.JTextField tuname;
    // End of variables declaration//GEN-END:variables
}
