package UI;/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import Transaction.TransactionAssociated;
import Transaction.Transaction;

import java.util.ArrayList;

/**
 *
 * @author saisuryavarshith
 */
public class ViewTransactionsUser extends javax.swing.JPanel {
    TransactionAssociated associated;
    /**
     * Creates new form viewacc
     */
    public ViewTransactionsUser(TransactionAssociated associated) {
        this.associated = associated;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ArrayList<Transaction> transactions = associated.getTransactions();
        String[][] transactionData = new String[transactions.size()][6];
        for (int i = 0; i < transactions.size() ; i++) {
            Transaction transaction = transactions.get(i);
            transactionData[i][0] = transaction.getDate();
            transactionData[i][1] = transaction.getTime();
            if(transaction.getSender() != null) {
                transactionData[i][2] = String.valueOf(transaction.getSender().getAccountNumber());
            } else {
                transactionData[i][2] = "Self";
            }

            if(transaction.getReceiver() != null) {
                transactionData[i][3] = String.valueOf(transaction.getReceiver().getAccountNumber());
            } else {
                transactionData[i][3] = "Cash";
            }

            transactionData[i][4] = String.valueOf(transaction.getAmount());
            transactionData[i][5] = String.valueOf(transaction.getAmount());
        }

        setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            transactionData,
            new String [] {
                "DATE", "TIME", "FROM", "TO", "AMOUNT SENT", "AMOUNT RECIEVED"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(249, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}






